-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 17, 2023 at 12:47 PM
-- Server version: 10.4.19-MariaDB
-- PHP Version: 8.0.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `lenders`
--

-- --------------------------------------------------------

--
-- Table structure for table `lenders`
--

CREATE TABLE `lenders` (
  `id` varchar(2) DEFAULT NULL,
  `name` varchar(44) DEFAULT NULL,
  `products` varchar(520) DEFAULT NULL,
  `criteria_id` varchar(11) DEFAULT NULL,
  `Property Details` enum('Purchase and Remortgage','Purchase','Remortgage') DEFAULT 'Purchase and Remortgage',
  `Property Type` enum('All','Residential','Semi Commercial','Commercial') DEFAULT 'All',
  `Is this property an ex-council property?` enum('Yes','No') DEFAULT 'Yes',
  `Is this property outside England or Wales?` enum('Yes','No') DEFAULT 'Yes',
  `Is this property a studio flat or bedsit?` enum('Yes','No') DEFAULT 'Yes',
  `Tax status?` enum('Basic','Higher','Additional') DEFAULT 'Basic',
  `Enter your Age:` int(11) DEFAULT NULL,
  `A first time buyer?` enum('Yes','No') DEFAULT 'Yes',
  `A foreign national or ex-pat?` enum('Yes','No') DEFAULT 'Yes',
  `A limited company?` enum('Yes','No') DEFAULT 'Yes',
  `Number of existing mortgages?` enum('Yes','No') DEFAULT 'No',
  `Number of Exisiting Mortgages?` int(11) DEFAULT NULL,
  `Will there be more than 4 tenants?` enum('Yes','No') DEFAULT 'Yes',
  `Will the house contain DSS tenants?` enum('Yes','No') DEFAULT 'Yes',
  `Will the house contain student tenants?` enum('Yes','No') DEFAULT 'Yes',
  `Will there be more than one tenancy agreement?` enum('Yes','No') DEFAULT 'Yes'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `lenders`
--

INSERT INTO `lenders` (`id`, `name`, `products`, `criteria_id`, `Property Details`, `Property Type`, `Is this property an ex-council property?`, `Is this property outside England or Wales?`, `Is this property a studio flat or bedsit?`, `Tax status?`, `Enter your Age:`, `A first time buyer?`, `A foreign national or ex-pat?`, `A limited company?`, `Number of existing mortgages?`, `Number of Exisiting Mortgages?`, `Will there be more than 4 tenants?`, `Will the house contain DSS tenants?`, `Will the house contain student tenants?`, `Will there be more than one tenancy agreement?`) VALUES
('13', 'Buy to let for individuals', '{\"ERC\": \"No\", \"for\": \"individuals\", \"dscr\": \"5.5%\", \"type\": \"residential\", \"Lender\": \"Buy to let for individuals\", \"incentive\": \"Yes\", \"iscr_basic\": \"125%\", \"icsr_higher\": \"145%\", \"intial_rate\": \"6.99%\", \"maximum_ltv\": \"75%\", \"product_fee\": \"1.50%\", \"product_name\": \"2 year fixed\", \"reversion_rate\": \"7.48%\", \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": 1000000, \"maximum_portfolio_size\": 5000000}', '2', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('14', 'Buy to let for individuals', '{\"ERC\": \"No\", \"for\": \"individuals\", \"dscr\": \"5.5%\", \"type\": \"residential\", \"Lender\": \"Buy to let for individuals\", \"incentive\": \"Yes\", \"iscr_basic\": \"125%\", \"icsr_higher\": \"145%\", \"intial_rate\": \"5.98%\", \"maximum_ltv\": \"75%\", \"product_fee\": \"u00a31,999\", \"product_name\": \"2 year discount off AMR\", \"reversion_rate\": \"7.48%\", \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": 1000000, \"maximum_portfolio_size\": 5000000}', '2', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('15', 'Buy to let for individuals', '{\"ERC\": \"No\", \"for\": \"individuals\", \"dscr\": \"4%\", \"type\": \"residential\", \"Lender\": \"Buy to let for individuals\", \"incentive\": \"Yes\", \"iscr_basic\": \"125%\", \"icsr_higher\": \"145%\", \"intial_rate\": \"7.29%\", \"maximum_ltv\": \"75%\", \"product_fee\": \"1.50%\", \"product_name\": \"5 year fixed\", \"reversion_rate\": \"7.48%\", \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": 1000000, \"maximum_portfolio_size\": 5000000}', '2', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('16', 'Buy to let for companies', '{\"ERC\": \"No\", \"for\": \"companies\", \"dscr\": \"5.5%\", \"type\": \"residential\", \"Lender\": \"Buy to let for companies\", \"incentive\": \"Yes\", \"iscr_basic\": \" 110%\", \"icsr_higher\": \"125% \", \"intial_rate\": \"6.99%\", \"maximum_ltv\": \"75%\", \"product_fee\": \"1.50%\", \"product_name\": \"2 year fixed\", \"reversion_rate\": \"7.48%\", \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": 1000000, \"maximum_portfolio_size\": 5000000}', '2', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('17', 'Buy to let for companies', '{\"ERC\": \"No\", \"for\": \"companies\", \"dscr\": \"5.5%\", \"type\": \"residential\", \"Lender\": \"Buy to let for companies\", \"incentive\": \"Yes\", \"iscr_basic\": \" 110%\", \"icsr_higher\": \"5.5%\", \"intial_rate\": \"5.98%\", \"maximum_ltv\": \"75%\", \"product_fee\": \"u00a31,999\", \"product_name\": \"2 year discount off AMR\", \"reversion_rate\": \"7.48%\", \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": 1000000, \"maximum_portfolio_size\": 5000000}', '2', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('18', 'Buy to let for companies', '{\"ERC\": \"No\", \"for\": \"companies\", \"dscr\": \"4%\", \"type\": \"residential\", \"Lender\": \"Buy to let for companies\", \"incentive\": \"Yes\", \"iscr_basic\": \" 110%\", \"icsr_higher\": \"125% \", \"intial_rate\": \"7.29%\", \"maximum_ltv\": \"75%\", \"product_fee\": \"1.50%\", \"product_name\": \"5 year fixed\", \"reversion_rate\": \"7.48%\", \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": 1000000, \"maximum_portfolio_size\": 5000000}', '2', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('19', 'Buy to let for HMOs and multi unit freeholds', '{\"ERC\": \"No\", \"for\": \"Individuals and Companies\", \"dscr\": \"5.5%\", \"type\": \"residential\", \"Lender\": \"Buy to let for HMOs and multi unit freeholds\", \"incentive\": \"Yes\", \"iscr_basic\": \" 125%\", \"icsr_higher\": \"140% \", \"intial_rate\": \"7.29%\", \"maximum_ltv\": \"75%\", \"product_fee\": \"1.50%\", \"product_name\": \"2 year fixed\", \"reversion_rate\": \"7.48%\", \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": 1000000, \"maximum_portfolio_size\": 5000000}', '2', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('20', 'Buy to let for HMOs and multi unit freeholds', '{\"ERC\": \"No\", \"for\": \"Individuals and Companies\", \"dscr\": \"5.5%\", \"type\": \"residential\", \"Lender\": \"Buy to let for HMOs and multi unit freeholds\", \"incentive\": \"Yes\", \"iscr_basic\": \" 125%\", \"icsr_higher\": \"140% \", \"intial_rate\": \"6.48%\", \"maximum_ltv\": \"75%\", \"product_fee\": \"u00a31,999\", \"product_name\": \"2 year discount off AMR\", \"reversion_rate\": \"7.48%\", \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": 1000000, \"maximum_portfolio_size\": 5000000}', '2', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('21', 'Buy to let for HMOs and multi unit freeholds', '{\"ERC\": \"No\", \"for\": \"Individuals and Companies\", \"dscr\": \"4%\", \"type\": \"residential\", \"Lender\": \"Buy to let for HMOs and multi unit freeholds\", \"incentive\": \"Yes\", \"iscr_basic\": \" 150%\", \"icsr_higher\": \"175% \", \"intial_rate\": \"7.44%\", \"maximum_ltv\": \"75%\", \"product_fee\": \"1.50%\", \"product_name\": \"5 year fixed\", \"reversion_rate\": \"7.48%\", \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": 1000000, \"maximum_portfolio_size\": 5000000}', '2', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('22', 'Buy to let multi property', '{\"ERC\": \"No\", \"for\": \"Individuals and companies with single residential investment property portfolios\", \"dscr\": \"5.5%\", \"type\": \"residential\", \"Lender\": \"Buy to let multi property\", \"incentive\": \"Yes\", \"iscr_basic\": \"110%\", \"icsr_higher\": \"125%\", \"intial_rate\": \"6.89%\", \"maximum_ltv\": \"75%\", \"product_fee\": \"1.50%\", \"product_name\": \"2 year fixed\", \"reversion_rate\": \"7.48%\", \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": 1000000, \"maximum_portfolio_size\": 5000000}', '2', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('23', 'Buy to let multi property', '{\"ERC\": \"No\", \"for\": \"Individuals and companies with single residential investment property portfolios\", \"dscr\": \"5.5%\", \"type\": \"residential\", \"Lender\": \"Buy to let multi property\", \"incentive\": \"Yes\", \"iscr_basic\": \"110%\", \"icsr_higher\": \"125%\", \"intial_rate\": \"5.88%\", \"maximum_ltv\": \"75%\", \"product_fee\": \"u00a31,999\", \"product_name\": \"2 year discount off AMR\", \"reversion_rate\": \"7.48%\", \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": 1000000, \"maximum_portfolio_size\": 5000000}', '2', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('24', 'Buy to let multi property', '{\"ERC\": \"No\", \"for\": \"Individuals and companies with single residential investment property portfolios\", \"dscr\": \"4%\", \"type\": \"residential\", \"Lender\": \"Buy to let multi property\", \"incentive\": \"Yes\", \"iscr_basic\": \" 120%\", \"icsr_higher\": \"145% \", \"intial_rate\": \"7.19%\", \"maximum_ltv\": \"75%\", \"product_fee\": \"1.50%\", \"product_name\": \"5 year fixed\", \"reversion_rate\": \"7.48%\", \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": 1000000, \"maximum_portfolio_size\": 5000000}', '2', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('25', 'Commercial mortgages product guide ', '{\"ERC\": \"No\", \"for\": \"industrial\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"Commercial mortgages product guide \", \"incentive\": \"NO\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": \"3.90%\", \"maximum_ltv\": \" 60% \", \"product_fee\": 0, \"product_name\": \"Commercial investment -Prime\", \"reversion_rate\": 0, \"property_details\": \"3 yearsu2019 experience 150% repayment cover from external income Property located in a UK town or city with no wants of repair \", \"maximum_loan_size\": \" million \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('26', 'Commercial mortgages product guide ', '{\"ERC\": \"No\", \"for\": \"industrial\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"Commercial mortgages product guide \", \"incentive\": \"NO\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": \"4.30%\", \"maximum_ltv\": \" 70% \", \"product_fee\": 0, \"product_name\": \"Commercial investment -Prime\", \"reversion_rate\": 0, \"property_details\": \"3 yearsu2019 experience 150% repayment cover from external income Property located in a UK town or city with no wants of repair \", \"maximum_loan_size\": \" million \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('27', 'Commercial mortgages product guide ', '{\"ERC\": \"No\", \"for\": \"industrial\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"Commercial mortgages product guide \", \"incentive\": \"NO\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": \"4.60%\", \"maximum_ltv\": \"Up to 60% \", \"product_fee\": 0, \"product_name\": \"Commercial investment -Variable\", \"reversion_rate\": 0, \"property_details\": \"Variable - 150% using gross rent at margin, plus Base Rate plus 3% \", \"maximum_loan_size\": \" million \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('28', 'Commercial mortgages product guide ', '{\"ERC\": \"No\", \"for\": \"industrial\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"Commercial mortgages product guide \", \"incentive\": \"NO\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": \"4.85%\", \"maximum_ltv\": \"Up to 70% \", \"product_fee\": 0, \"product_name\": \"Commercial investment -Variable\", \"reversion_rate\": 0, \"property_details\": \"Variable - 150% using gross rent at margin, plus Base Rate plus 3% \", \"maximum_loan_size\": \" million \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('29', 'Commercial mortgages product guide ', '{\"ERC\": \"No\", \"for\": \"industrial\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"Commercial mortgages product guide \", \"incentive\": \"NO\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": \"5.15% \", \"maximum_ltv\": \"Over 70% \", \"product_fee\": 0, \"product_name\": \"Commercial investment -Variable\", \"reversion_rate\": 0, \"property_details\": \"Variable - 150% using gross rent at margin, plus Base Rate plus 3% \", \"maximum_loan_size\": \" million \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('30', 'Commercial mortgages product guide ', '{\"ERC\": \"No\", \"for\": \"industrial\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"Commercial mortgages product guide \", \"incentive\": \"NO\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": \"8.00%\", \"maximum_ltv\": \"Up to 60% \", \"product_fee\": 0, \"product_name\": \"Commercial investment -5 year fixed \", \"reversion_rate\": 0, \"property_details\": \"Fixed u2013 150% at pay rate Interest only loans must evidence affordability over a 25-year amortising term \", \"maximum_loan_size\": \" million \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('31', 'Commercial mortgages product guide ', '{\"ERC\": \"No\", \"for\": \"industrial\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"Commercial mortgages product guide \", \"incentive\": \"NO\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": \"8.25%\", \"maximum_ltv\": \"Up to 70% \", \"product_fee\": 0, \"product_name\": \"Commercial investment -5 year fixed \", \"reversion_rate\": 0, \"property_details\": \"Fixed u2013 150% at pay rate Interest only loans must evidence affordability over a 25-year amortising term \", \"maximum_loan_size\": \" million \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('32', 'Commercial mortgages product guide ', '{\"ERC\": \"No\", \"for\": \"industrial\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"Commercial mortgages product guide \", \"incentive\": \"NO\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": \"8.55%\", \"maximum_ltv\": \"Over 70% \", \"product_fee\": 0, \"product_name\": \"Commercial investment -5 year fixed \", \"reversion_rate\": 0, \"property_details\": \"Fixed u2013 150% at pay rate Interest only loans must evidence affordability over a 25-year amortising term \", \"maximum_loan_size\": \" million \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('33', 'Commercial mortgages product guide ', '{\"ERC\": \"No\", \"for\": \"industrial\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"Commercial mortgages product guide \", \"incentive\": \"NO\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": \"7.75%\", \"maximum_ltv\": \"Up to 65% \", \"product_fee\": 0, \"product_name\": \"Commercial investment -10 year fixed u00a0\", \"reversion_rate\": 0, \"property_details\": \"EPC rating A-C Maximum LTV of 65% \", \"maximum_loan_size\": \" million \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('34', 'Aspen Bridging', '{\"ERC\": [\"1.00%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"0.99%\"], \"maximum_ltv\": [\"75%\"], \"product_fee\": 0, \"product_name\": \"Dev Exit & Refurb BRIDGE RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('35', 'Aspen Bridging', '{\"ERC\": [\"1.50%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"0.99%\"], \"maximum_ltv\": [\"75%\"], \"product_fee\": 0, \"product_name\": \"Dev Exit & Refurb BRIDGE RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('36', 'Aspen Bridging', '{\"ERC\": [\"1.00%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"0.94%\"], \"maximum_ltv\": [\"1.00%\"], \"product_fee\": 0, \"product_name\": \"Residential BRIDGE RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('37', 'Aspen Bridging', '{\"ERC\": [\"1.50%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"0.94%\"], \"maximum_ltv\": [\"1.50%\"], \"product_fee\": 0, \"product_name\": \"Residential BRIDGE RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('38', 'Aspen Bridging', '{\"ERC\": [\"1.00%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"0.89%\"], \"maximum_ltv\": [\"60%\"], \"product_fee\": 0, \"product_name\": \"Residential BRIDGE RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('39', 'Aspen Bridging', '{\"ERC\": [\"1.50%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"0.89%\"], \"maximum_ltv\": [\"60%\"], \"product_fee\": 0, \"product_name\": \"Residential BRIDGE RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('40', 'Aspen Bridging', '{\"ERC\": [\"1.00%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"0.94%\"], \"maximum_ltv\": [\"70%\"], \"product_fee\": 0, \"product_name\": \"Semi-Commercial BRIDGE RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('41', 'Aspen Bridging', '{\"ERC\": [\"1.50%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"0.94%\"], \"maximum_ltv\": [\"70%\"], \"product_fee\": 0, \"product_name\": \"Semi-Commercial BRIDGE RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('42', 'Aspen Bridging', '{\"ERC\": [\"1.00%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"0.99%\"], \"maximum_ltv\": [\"70%\"], \"product_fee\": 0, \"product_name\": \"70% BRIDGE RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('43', 'Aspen Bridging', '{\"ERC\": [\"1.50%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"0.99%\"], \"maximum_ltv\": [\"70%\"], \"product_fee\": 0, \"product_name\": \"70% BRIDGE RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('44', 'Aspen Bridging', '{\"ERC\": [\"1.00%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"0.94%\"], \"maximum_ltv\": [\"70%\"], \"product_fee\": 0, \"product_name\": \"HMO BRIDGE RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('45', 'Aspen Bridging', '{\"ERC\": [\"1.50%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"0.94%\"], \"maximum_ltv\": [\"70%\"], \"product_fee\": 0, \"product_name\": \"HMO BRIDGE RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('46', 'Aspen Bridging', '{\"ERC\": [\"1.00%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"8.49%\"], \"maximum_ltv\": [\"75%\"], \"product_fee\": [\"1.00%\"], \"product_name\": \"Residental & HMO BTL RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('47', 'Aspen Bridging', '{\"ERC\": [\"1.00%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"8.49%\"], \"maximum_ltv\": [\"75%\"], \"product_fee\": [\"1.00%\"], \"product_name\": \"Residental & HMO BTL RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('48', 'Aspen Bridging', '{\"ERC\": [\"1.50%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"8.49%\"], \"maximum_ltv\": [\"75%\"], \"product_fee\": [\"1.00%\"], \"product_name\": \"Residental & HMO BTL RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('49', 'Aspen Bridging', '{\"ERC\": [\"1.00%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"8.49%\"], \"maximum_ltv\": [\"75%\"], \"product_fee\": [\"1.00%\"], \"product_name\": \"Semi-Commercial BTL RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('50', 'Aspen Bridging', '{\"ERC\": [\"1.00%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"8.49%\"], \"maximum_ltv\": [\"75%\"], \"product_fee\": [\"1.00%\"], \"product_name\": \"Semi-Commercial BTL RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('51', 'Aspen Bridging', '{\"ERC\": [\"1.50%\"], \"for\": \"\", \"dscr\": 0, \"type\": \"\", \"Lender\": \"Aspen Bridging\", \"incentive\": \"No\", \"iscr_basic\": 0, \"icsr_higher\": 0, \"intial_rate\": [\"8.49%\"], \"maximum_ltv\": [\"75%\"], \"product_fee\": [\"1.00%\"], \"product_name\": \"Semi-Commercial BTL RATES\", \"reversion_rate\": 0, \"property_details\": \"\", \"maximum_loan_size\": 0, \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('52', 'skiptoninternational', '{\"ERC\": \"No\", \"for\": \"individuals\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"skiptoninternational\", \"incentive\": \"No\", \"iscr_basic\": 0, \"intial_rate\": 0, \"maximum_ltv\": 0, \"product_fee\": \"Fee Free \", \"product_name\": \"3-Year Tracker\", \"reversion_rate\": 0, \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": \"u00a3250,000 \", \"minimum_loan_size\": \"u00a3100,000 to\", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('53', 'skiptoninternational', '{\"ERC\": \"No\", \"for\": \"individuals\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"skiptoninternational\", \"incentive\": \"No\", \"iscr_basic\": 0, \"intial_rate\": 0, \"maximum_ltv\": 0, \"product_fee\": \"Fee Free \", \"product_name\": \"Fee Free \", \"reversion_rate\": 0, \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": \"u00a3500,000 \", \"minimum_loan_size\": \"u00a3250,001 to \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('54', 'skiptoninternational', '{\"ERC\": \"No\", \"for\": \"individuals\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"skiptoninternational\", \"incentive\": \"No\", \"iscr_basic\": 0, \"intial_rate\": 0, \"maximum_ltv\": 0, \"product_fee\": \"Fee Free \", \"product_name\": \"Fee Free \", \"reversion_rate\": 0, \"property_details\": \"Purchase and Remortgage\", \"minimum_loan_size\": \"u00a3500,000 \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('55', 'skiptoninternational', '{\"ERC\": \"No\", \"for\": \"individuals\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"skiptoninternational\", \"incentive\": \"No\", \"iscr_basic\": 0, \"intial_rate\": 0, \"maximum_ltv\": 0, \"product_fee\": \"Fee Free \", \"product_name\": \"5-Year Fixed \", \"reversion_rate\": 0, \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": \"u00a3250,000 \", \"minimum_loan_size\": \"u00a3100,000 to\", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('56', 'skiptoninternational', '{\"ERC\": \"No\", \"for\": \"individuals\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"skiptoninternational\", \"incentive\": \"No\", \"iscr_basic\": 0, \"intial_rate\": 0, \"maximum_ltv\": 0, \"product_fee\": \"Fee Free \", \"product_name\": \"5-Year Fixed \", \"reversion_rate\": 0, \"property_details\": \"Purchase and Remortgage\", \"maximum_loan_size\": \"u00a3500,000 \", \"minimum_loan_size\": \"u00a3250,001 to \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes'),
('57', 'skiptoninternational', '{\"ERC\": \"No\", \"for\": \"individuals\", \"dscr\": 0, \"type\": \"Commercial\", \"Lender\": \"skiptoninternational\", \"incentive\": \"No\", \"iscr_basic\": 0, \"intial_rate\": 0, \"maximum_ltv\": 0, \"product_fee\": \"Fee Free \", \"product_name\": \"5-Year Fixed \", \"reversion_rate\": 0, \"property_details\": \"Purchase and Remortgage\", \"minimum_loan_size\": \"u00a3500,000 \", \"maximum_portfolio_size\": 0}', '', 'Purchase and Remortgage', 'All', 'Yes', 'Yes', 'Yes', 'Basic', NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `lenders`
--
ALTER TABLE `lenders`
  ADD UNIQUE KEY `id` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
